#!/usr/bin/env bash
# Fails when requirements-action.in, pyproject.toml, and requirements-action.txt disagree (Task 7
# interface). Two independent checks, both must pass:
#   1. requirements-action.in's runtime specifiers are exactly pyproject.toml's
#      [project.dependencies] (the build-system's hatchling has no version range in pyproject.toml
#      to compare against, by design -- see requirements-action.in's own comment).
#   2. requirements-action.txt (checked in) is byte-identical, modulo its autogenerated header, to
#      a fresh `uv pip compile --generate-hashes` run of requirements-action.in.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

if ! command -v uv >/dev/null 2>&1; then
    echo "verify-action-lock: uv is required but not found on PATH" >&2
    exit 1
fi

echo "verify-action-lock: checking requirements-action.in against pyproject.toml dependencies..."

if ! python3 - "$repo_root" <<'PY'
import sys
import tomllib
from pathlib import Path

repo_root = Path(sys.argv[1])
pyproject = tomllib.loads((repo_root / "pyproject.toml").read_text())
expected = set(pyproject["project"]["dependencies"])

actual = set()
for line in (repo_root / "requirements-action.in").read_text().splitlines():
    stripped = line.strip()
    if not stripped or stripped.startswith("#") or stripped == "hatchling":
        continue
    actual.add(stripped)

missing = expected - actual
extra = actual - expected
if missing or extra:
    if missing:
        print(f"requirements-action.in is missing pyproject.toml dependencies: {sorted(missing)}", file=sys.stderr)
    if extra:
        print(f"requirements-action.in has entries not declared in pyproject.toml: {sorted(extra)}", file=sys.stderr)
    sys.exit(1)
PY
then
    echo "verify-action-lock: requirements-action.in and pyproject.toml disagree" >&2
    exit 1
fi

echo "verify-action-lock: regenerating the lock in a temporary path and comparing..."

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

# Seed the temp output with the checked-in lock *before* compiling into it: `uv pip compile`
# treats a pre-existing output file at -o as a preference source and keeps every still-valid pin
# as-is. Compiling into a virgin path instead makes uv re-resolve every loosely-constrained
# package (including unconstrained ones like hatchling) to whatever is newest on PyPI right now --
# which would fail this check on any unrelated upstream release, with nothing in this repo having
# changed. Seeding preserves real drift detection (a genuine .in/pyproject.toml change still
# produces a diff) while eliminating that false positive.
cp requirements-action.txt "$tmp_dir/requirements-action.txt"
uv pip compile --generate-hashes --python-version 3.12 \
    -o "$tmp_dir/requirements-action.txt" requirements-action.in >/dev/null

# Skip each file's first 2 header lines: uv embeds the -o path it was given there, which never
# matches the checked-in file's own header even when the locked contents underneath are identical.
if ! diff -u <(tail -n +3 requirements-action.txt) <(tail -n +3 "$tmp_dir/requirements-action.txt"); then
    echo "verify-action-lock: requirements-action.txt is stale -- regenerate it with:" >&2
    echo "  uv pip compile --generate-hashes --python-version 3.12 -o requirements-action.txt requirements-action.in" >&2
    exit 1
fi

echo "verify-action-lock: requirements-action.in, pyproject.toml, and requirements-action.txt agree."
